-- Controlled memory rebuild: additive dream/staging metadata.
-- Applies only beside the live memory path. No live wake/recall query changes.

BEGIN;

ALTER TABLE agentic_memory.facts_staging
  ADD COLUMN IF NOT EXISTS derived_by text,
  ADD COLUMN IF NOT EXISTS derived_kind text,
  ADD COLUMN IF NOT EXISTS source_issue_ids uuid[],
  ADD COLUMN IF NOT EXISTS source_comment_ids uuid[],
  ADD COLUMN IF NOT EXISTS source_communication_ids uuid[],
  ADD COLUMN IF NOT EXISTS source_fact_ids bigint[],
  ADD COLUMN IF NOT EXISTS source_staging_ids bigint[],
  ADD COLUMN IF NOT EXISTS contradicts_fact_ids bigint[],
  ADD COLUMN IF NOT EXISTS supersedes_fact_ids bigint[],
  ADD COLUMN IF NOT EXISTS candidate_significance smallint,
  ADD COLUMN IF NOT EXISTS retention_recommendation text,
  ADD COLUMN IF NOT EXISTS dream_batch_id text;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'facts_staging_candidate_significance_chk'
      AND conrelid = 'agentic_memory.facts_staging'::regclass
  ) THEN
    ALTER TABLE agentic_memory.facts_staging
      ADD CONSTRAINT facts_staging_candidate_significance_chk
      CHECK (candidate_significance IS NULL OR candidate_significance BETWEEN 1 AND 10);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'facts_staging_retention_recommendation_chk'
      AND conrelid = 'agentic_memory.facts_staging'::regclass
  ) THEN
    ALTER TABLE agentic_memory.facts_staging
      ADD CONSTRAINT facts_staging_retention_recommendation_chk
      CHECK (
        retention_recommendation IS NULL
        OR retention_recommendation IN ('promote','keep_staged','archive_leaf','decline')
      );
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS agentic_memory.dream_batches (
  batch_id text PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  model text NOT NULL,
  source_kind text NOT NULL,
  status text NOT NULL DEFAULT 'running',
  source_count integer NOT NULL DEFAULT 0,
  candidate_count integer NOT NULL DEFAULT 0,
  notes text,
  CONSTRAINT dream_batches_status_chk CHECK (status IN ('running','ok','error')),
  CONSTRAINT dream_batches_source_kind_chk CHECK (source_kind IN ('closed_issue','customer_email_window','self_note_cluster','pve_import_cluster','mixed'))
);

CREATE TABLE IF NOT EXISTS agentic_memory.dream_source_windows (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id text NOT NULL REFERENCES agentic_memory.dream_batches(batch_id) ON DELETE CASCADE,
  source_kind text NOT NULL,
  source_id text NOT NULL,
  source_path text NOT NULL,
  packet_sha256 char(64) NOT NULL,
  scope text,
  agent_owner uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT dream_source_windows_source_path_absolute CHECK (source_path LIKE '/%')
);

CREATE INDEX IF NOT EXISTS dream_source_windows_batch_idx
  ON agentic_memory.dream_source_windows(batch_id);

CREATE INDEX IF NOT EXISTS facts_staging_dream_batch_idx
  ON agentic_memory.facts_staging(dream_batch_id);

CREATE INDEX IF NOT EXISTS facts_staging_derived_idx
  ON agentic_memory.facts_staging(derived_by, derived_kind, status);

INSERT INTO agentic_memory.schema_version (version, notes)
VALUES (5, 'controlled memory rebuild: additive dream/staging metadata')
ON CONFLICT (version) DO NOTHING;

COMMIT;

