-- Controlled memory rebuild: raw source inventory/import layer.
-- This replaces trust in old source_chunks with a fresh, repeatable source walk.

BEGIN;

CREATE TABLE IF NOT EXISTS agentic_memory.raw_source_walks (
  walk_id text PRIMARY KEY,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  status text NOT NULL DEFAULT 'running',
  source_count integer NOT NULL DEFAULT 0,
  notes text,
  CONSTRAINT raw_source_walks_status_chk CHECK (status IN ('running','ok','error'))
);

CREATE TABLE IF NOT EXISTS agentic_memory.raw_sources (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_kind text NOT NULL,
  source_uri text NOT NULL UNIQUE,
  source_path text,
  external_id text,
  content_sha256 char(64) NOT NULL,
  content text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  imported_at timestamptz NOT NULL DEFAULT now(),
  source_mtime timestamptz,
  byte_size bigint,
  walk_id text REFERENCES agentic_memory.raw_source_walks(walk_id) ON DELETE SET NULL,
  active boolean NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS raw_sources_kind_idx
  ON agentic_memory.raw_sources(source_kind);

CREATE INDEX IF NOT EXISTS raw_sources_walk_idx
  ON agentic_memory.raw_sources(walk_id);

CREATE INDEX IF NOT EXISTS raw_sources_metadata_gin
  ON agentic_memory.raw_sources USING gin(metadata);

INSERT INTO agentic_memory.schema_version (version, notes)
VALUES (6, 'controlled memory rebuild: fresh raw source walk/import layer')
ON CONFLICT (version) DO NOTHING;

COMMIT;

