-- Controlled Memory Rebuild: grounded source windows and embeddings.
-- Embeddings are indexes over source windows, not source of truth.

ALTER TABLE agentic_memory.raw_sources
  ADD COLUMN IF NOT EXISTS company_id uuid,
  ADD COLUMN IF NOT EXISTS customer_id uuid,
  ADD COLUMN IF NOT EXISTS project_key text,
  ADD COLUMN IF NOT EXISTS domain_name text,
  ADD COLUMN IF NOT EXISTS agent_slug text,
  ADD COLUMN IF NOT EXISTS scope text;

CREATE INDEX IF NOT EXISTS raw_sources_company_idx
  ON agentic_memory.raw_sources (company_id);

CREATE INDEX IF NOT EXISTS raw_sources_customer_idx
  ON agentic_memory.raw_sources (customer_id);

CREATE INDEX IF NOT EXISTS raw_sources_project_idx
  ON agentic_memory.raw_sources (project_key);

CREATE INDEX IF NOT EXISTS raw_sources_domain_idx
  ON agentic_memory.raw_sources (domain_name);

CREATE INDEX IF NOT EXISTS raw_sources_agent_idx
  ON agentic_memory.raw_sources (agent_slug);

CREATE INDEX IF NOT EXISTS raw_sources_scope_idx
  ON agentic_memory.raw_sources (scope);

CREATE TABLE IF NOT EXISTS agentic_memory.source_windows (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  raw_source_id bigint NOT NULL REFERENCES agentic_memory.raw_sources(id) ON DELETE CASCADE,
  window_uri text NOT NULL UNIQUE,
  content_sha256 char(64) NOT NULL,
  content text NOT NULL,
  start_line integer,
  end_line integer,
  start_char integer,
  end_char integer,
  heading_path text,
  semantic_kind text,
  token_estimate integer,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  company_id uuid,
  customer_id uuid,
  project_key text,
  domain_name text,
  agent_slug text,
  scope text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  search_doc tsvector GENERATED ALWAYS AS (
    setweight(to_tsvector('english', coalesce(heading_path, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(content, '')), 'B')
  ) STORED
);

CREATE INDEX IF NOT EXISTS source_windows_raw_source_idx
  ON agentic_memory.source_windows (raw_source_id);

CREATE INDEX IF NOT EXISTS source_windows_company_idx
  ON agentic_memory.source_windows (company_id);

CREATE INDEX IF NOT EXISTS source_windows_customer_idx
  ON agentic_memory.source_windows (customer_id);

CREATE INDEX IF NOT EXISTS source_windows_project_idx
  ON agentic_memory.source_windows (project_key);

CREATE INDEX IF NOT EXISTS source_windows_domain_idx
  ON agentic_memory.source_windows (domain_name);

CREATE INDEX IF NOT EXISTS source_windows_agent_idx
  ON agentic_memory.source_windows (agent_slug);

CREATE INDEX IF NOT EXISTS source_windows_scope_idx
  ON agentic_memory.source_windows (scope);

CREATE INDEX IF NOT EXISTS source_windows_search_idx
  ON agentic_memory.source_windows USING gin (search_doc);

CREATE TABLE IF NOT EXISTS agentic_memory.source_embeddings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  window_id bigint NOT NULL REFERENCES agentic_memory.source_windows(id) ON DELETE CASCADE,
  embedding_model text NOT NULL,
  embedding vector(1024) NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  embedded_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (window_id, embedding_model)
);

CREATE INDEX IF NOT EXISTS source_embeddings_window_idx
  ON agentic_memory.source_embeddings (window_id);

CREATE INDEX IF NOT EXISTS source_embeddings_embedding_hnsw
  ON agentic_memory.source_embeddings USING hnsw (embedding vector_cosine_ops)
  WITH (m='16', ef_construction='64');

INSERT INTO agentic_memory.schema_version (version, notes)
VALUES (7, 'controlled rebuild source windows and grounded embeddings')
ON CONFLICT (version) DO NOTHING;
