-- Controlled Memory Rebuild: compact memory windows.
-- Source windows are evidence. Compact memory windows are the prompt/retrieval
-- unit agents should normally consume.

CREATE TABLE IF NOT EXISTS agentic_memory.compact_memory_windows (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  compact_uri text NOT NULL UNIQUE,
  source_window_ids bigint[] NOT NULL DEFAULT '{}',
  raw_source_ids bigint[] NOT NULL DEFAULT '{}',
  content text NOT NULL,
  summary text,
  episode_kind text,
  outcome text,
  company_id uuid,
  customer_id uuid,
  project_key text,
  domain_name text,
  agent_slug text,
  scope text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  search_doc tsvector GENERATED ALWAYS AS (
    setweight(to_tsvector('english', coalesce(summary, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(content, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(outcome, '')), 'A')
  ) STORED
);

CREATE INDEX IF NOT EXISTS compact_memory_company_idx
  ON agentic_memory.compact_memory_windows (company_id);

CREATE INDEX IF NOT EXISTS compact_memory_customer_idx
  ON agentic_memory.compact_memory_windows (customer_id);

CREATE INDEX IF NOT EXISTS compact_memory_project_idx
  ON agentic_memory.compact_memory_windows (project_key);

CREATE INDEX IF NOT EXISTS compact_memory_domain_idx
  ON agentic_memory.compact_memory_windows (domain_name);

CREATE INDEX IF NOT EXISTS compact_memory_agent_idx
  ON agentic_memory.compact_memory_windows (agent_slug);

CREATE INDEX IF NOT EXISTS compact_memory_scope_idx
  ON agentic_memory.compact_memory_windows (scope);

CREATE INDEX IF NOT EXISTS compact_memory_episode_idx
  ON agentic_memory.compact_memory_windows (episode_kind);

CREATE INDEX IF NOT EXISTS compact_memory_search_idx
  ON agentic_memory.compact_memory_windows USING gin (search_doc);

CREATE TABLE IF NOT EXISTS agentic_memory.compact_memory_embeddings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  compact_window_id bigint NOT NULL REFERENCES agentic_memory.compact_memory_windows(id) ON DELETE CASCADE,
  embedding_model text NOT NULL,
  embedding vector(1024) NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  embedded_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (compact_window_id, embedding_model)
);

CREATE INDEX IF NOT EXISTS compact_memory_embeddings_window_idx
  ON agentic_memory.compact_memory_embeddings (compact_window_id);

CREATE INDEX IF NOT EXISTS compact_memory_embeddings_hnsw
  ON agentic_memory.compact_memory_embeddings USING hnsw (embedding vector_cosine_ops)
  WITH (m='16', ef_construction='64');

INSERT INTO agentic_memory.schema_version (version, notes)
VALUES (8, 'controlled rebuild compact memory windows')
ON CONFLICT (version) DO NOTHING;
